# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0601acdad0218b5874b7aef9b4750c47c5d2ece5f4707112134d06992b9b023115e6783d932fb430bb2999c560ac98f087793d0bd7672b0e473d677597baff61

test:
  secret_key_base: a39cc7d1c3605e21f404b082cee20ea6553b1a2abdfee820661117b0e00f3e0dacb54410d4ae719107c2298bbe478d124c1ed2b1f5e4eb538f1f5533e1021fab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
